x = int(input("Please tell me your age: "))
print(f"You are currently {x} years old")
print(f"In 10 years, you'll be {x+10} years old.")
print(f"In 20 years, you'll be {x+20} years old.")
print(f"In 30 years, you'll be {x+30} years old.")
